apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: smart-home
data:
  influxdb.yml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb-service:8086
        jsonData:
          version: Flux
          organization: smarthome
          defaultBucket: sensor_data
          tlsSkipVerify: true
        secureJsonData:
          token: my-super-secret-auth-token

