apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-publisher
  namespace: smart-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-publisher
  template:
    metadata:
      labels:
        app: sensor-publisher
    spec:
      containers:
      - name: sensor-publisher
        image: yourusername/smart-home-publisher:latest  # Replace with your DockerHub username
        env:
        - name: MQTT_BROKER
          value: mosquitto-service
        - name: MQTT_PORT
          value: "1883"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"

