apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: smart-home
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: websocket
    port: 9001
    targetPort: 9001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: smart-home
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8086
    targetPort: 8086
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: smart-home
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
  namespace: smart-home
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 31883
  - name: websocket
    port: 9001
    targetPort: 9001
    nodePort: 31901
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: smart-home
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-external
  namespace: smart-home
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    nodePort: 30806
  type: NodePort

