name: Build and Push to DockerHub

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [publisher, subscriber]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/smart-home-${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.${{ matrix.service }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test docker-compose setup
      run: |
        # Create required directories
        mkdir -p mosquitto/{config,data,log}
        mkdir -p grafana/provisioning/{dashboards,datasources}
        
        # Create basic mosquitto config
        cat > mosquitto/config/mosquitto.conf << EOF
        listener 1883 0.0.0.0
        allow_anonymous true
        persistence true
        persistence_location /mosquitto/data/
        log_dest stdout
        EOF
        
        # Update compose to use built images
        sed -i 's|build:|#build:|g' docker-compose.yml
        sed -i 's|context: .|#context: .|g' docker-compose.yml
        sed -i 's|dockerfile: Dockerfile.publisher|#dockerfile: Dockerfile.publisher|g' docker-compose.yml
        sed -i 's|dockerfile: Dockerfile.subscriber|#dockerfile: Dockerfile.subscriber|g' docker-compose.yml
        sed -i '/sensor-publisher:/a\    image: ${{ env.DOCKERHUB_USERNAME }}/smart-home-publisher:latest' docker-compose.yml
        sed -i '/data-subscriber:/a\    image: ${{ env.DOCKERHUB_USERNAME }}/smart-home-subscriber:latest' docker-compose.yml
        
        # Test compose
        docker compose config
        docker compose up -d
        sleep 60
        docker compose ps
        docker compose logs
        docker compose down
